# Generated by Django 5.2.8 on 2025-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('tutor', models.CharField(max_length=100, verbose_name='Tutor')),
                ('programa', models.CharField(max_length=150, verbose_name='Programa')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('palabras_clave', models.CharField(help_text='Separadas por comas', max_length=300, verbose_name='Palabras Clave')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
